# Generated by Django 4.2.5 on 2024-01-14 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0010_alter_record_is_available'),
    ]

    operations = [
        migrations.AddField(
            model_name='author',
            name='birth_year',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='author',
            name='death_year',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='record',
            name='release_year',
            field=models.IntegerField(blank=True, default=None, null=True),
        ),
    ]
