# Generated by Django 4.2.5 on 2024-01-14 16:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0011_author_birth_year_author_death_year_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='description',
            field=models.CharField(default='brak', max_length=300),
        ),
    ]
