# Generated by Django 4.2.5 on 2024-01-14 16:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('website', '0013_alter_author_death_year'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='author',
            name='death_year',
        ),
    ]
